name: Run Anchor Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-test@v2
        with:
          node-version: '20.11.0'
          solana-cli-version: '2.2.3'
          anchor-version: '0.31.2'
